version: '3.8'

services:
  backend:
    build: .
    container_name: fast_food_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/food_db
      # Internal Docker Network Connection (Backend -> MinIO Container)
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=False
      # Config for Backend to authenticate
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # External URL for Frontend/Clients to access images
      - MINIO_EXTERNAL_ENDPOINT=http://localhost:9000
    depends_on:
      - db
      - minio

  db:
    image: postgres:13
    container_name: fast_food_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=food_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist DB data

  minio:
    image: minio/minio
    container_name: fast_food_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Persist MinIO data

# Persistent Volumes (Data survives docker-compose down)
volumes:
  postgres_data:
  minio_data:
